environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - node --version
  - npm --version
  - bash script/build
  - bash script/test
