#!/usr/bin/env bash

rm -rf dist
mkdir -p dist
CARGO_INCREMENTAL=0 RUSTFLAGS="-C debuginfo=0 -C opt-level=s -C lto -C panic=abort" cargo build --release --target wasm32-unknown-unknown
wasm-bindgen ../target/wasm32-unknown-unknown/release/xray_wasm.wasm --out-dir dist
wasm-opt -O3 -o ./dist/xray_wasm_bg.wasm ./dist/xray_wasm_bg.wasm
