#!/bin/bash

set -e

cd xray_server; cargo build "$@"; cd -
cd xray_cli; cargo build "$@"; cd -
cd xray_wasm; script/build; cd -
cd xray_electron; yarn install; cd -
cd xray_browser; script/build; cd -
